### ISSUE TITLE
Parts and Threshold validation

### ISSUE THREAD

**Issue by enrichman** [enrichman/stegosecrets#1]
Threshold cannot be more than the parts:

```
Error: failed to initilize writer: parts cannot be less than threshold
```

We should perform a very basic check during the creation of the Encrypter:

https://github.com/enrichman/stegosecrets/blob/main/internal/encrypt/encrypt.go#L22-L33

**Comment by misantron** [comment]
Any other validations should be executed or just parts and threshold comparison?

**Comment by misantron** [comment]
@enrichman

**Comment by enrichman** [comment]
Other validations are done with the functional opts, but I would check if the value are ok, because I think I added a wrong value (>256 instead of >255).

So yes, just the parts/threshold comparison. 👍

**Comment by misantron** [comment]
I'll take it
