### ISSUE TITLE
Picsum client hangs

### ISSUE THREAD

**Issue by enrichman** [enrichman/stegosecrets#2]
This needs a bit of investigation but the picsum cilent hanged while doing the requests.

https://github.com/enrichman/stegosecrets/blob/main/internal/cli/images.go

We should probably see if there is a rate limiter, handling that, or at least using a context with timeout to fail gracefully.

**Comment by giulianopz** [comment]
Hi @enrichman, could you please assign it to me? Just to have an easy-peasy issue for the Hacktoberfest 😁

**Comment by enrichman** [comment]
Thank you, sure!

**Comment by giulianopz** [comment]
#23
