### ISSUE TITLE
Add progress bar while downloading images

### ISSUE THREAD

**Issue by enrichman** [enrichman/stegosecrets#26]
The `images` command obviously takes a while to download the images.

It would be cool to add a progressbar (https://github.com/schollz/progressbar) to show the progress of it.

https://github.com/enrichman/stegosecrets/blob/main/internal/cli/images.go#L37-L63

It would be nice to see the total content length of the responses and the download progress (instead of the number of the downloaded images), but this could be a bit more "complex".

**Comment by void-developer** [comment]
I'm working on the number of images part. The contentLength might be a little bit more complex since the contentLength is set to -1, but I'll work on that too. Could you please assign it to me?

**Comment by enrichman** [comment]
So are you working also on https://github.com/enrichman/stegosecrets/issues/25 ? Should I assign also that one to you?

That's ok, but let's do two different PR for the two different issues. :+1:

**Comment by enrichman** [comment]
I would say to add only the progress with the number of the images as a start, and we can improve it later.

**Comment by void-developer** [comment]
Ok the 25 is fine, I thought they weren't really dependent on each other. I'll be doing 25

**Comment by enrichman** [comment]
No, I thought that when you said `I'm working on the number of images part` you were talking about the #25, but if you prefer this one let's keep it like this and lets leave the other issue to someone else. :smile:
