### ISSUE TITLE
Decrypt from image is not working

### ISSUE THREAD

**Issue by enrichman** [enrichman/stegosecrets#27]
It seems that this feature is not yet implemented (the func is the same of the `.key` file):

https://github.com/enrichman/stegosecrets/blob/1fcc29f07b68b648f511208d1da574c81438d59e/internal/decrypt/decrypt.go#L68-L79

We are completely missing the steganography decryption.

**Comment by mastrogiovanni** [comment]
I can take this one. Can you assign it to me?

**Comment by enrichman** [comment]
Sure, thanks! This is an important one!

**Comment by enrichman** [comment]
Hey @mastrogiovanni, any updates on this one?
