### ISSUE TITLE
Improve logger with `-v/--verbose` flag

### ISSUE THREAD

**Issue by enrichman** [enrichman/stegosecrets#28]
There is a pretty basic logger with a debugEnabled flag.

We should add a `-v/--verbose` flag to enable it.

https://github.com/enrichman/stegosecrets/blob/1fcc29f07b68b648f511208d1da574c81438d59e/internal/log/logger.go#L12-L14

**Comment by ellisonleao** [comment]
can i try this one?

**Comment by enrichman** [comment]
Ehy @ellisonleao, thank you, sure. Let me assign it to you.
And if you like the project please star it! :star2: :rocket:
