### ISSUE TITLE
Improve logger with `-s/--silent` flag

### ISSUE THREAD

**Issue by enrichman** [enrichman/stegosecrets#29]
We could improve the logger to support a silent/quiet mode and disable the logging.

An easy way to do this could be to use a `SilentLogger` implementation with nop funcs.

https://github.com/enrichman/stegosecrets/blob/1fcc29f07b68b648f511208d1da574c81438d59e/internal/log/logger.go#L7-L10

**Comment by andreaSilv** [comment]
Hi @enrichman any possible to have this issue assigned?

**Comment by enrichman** [comment]
Sure thing! Thanks.
