### ISSUE TITLE
Add width and height flags to images command

### ISSUE THREAD

**Issue by enrichman** [enrichman/stegosecrets#3]
The images command is hardcoded. We could provide a couple of flags (`-w`, `-h`) to specify the width and height of the downloaded images.

https://github.com/enrichman/stegosecrets/blob/main/internal/cli/images.go

**Comment by Tashima42** [comment]
Hey, I wan't to try to tackle this issue.

These flags would affect only this line?
https://github.com/enrichman/stegosecrets/blob/63cec30f012ca3ff808a340825b5288bc5db082a/internal/cli/images.go#L24

**Comment by enrichman** [comment]
Hey @Tashima42 , thank you. Yes exactly, easy peasy! 😄 
Can I assign it to you?

**Comment by Tashima42** [comment]
Yes!

But, we can't use `-h`, it's already registered as a shorthand for `--help`, an alternative would be use just `--width` and `--height` without the shorthands, what do you think?

**Comment by enrichman** [comment]
You're right. Yes, let's go for it.
