### ISSUE TITLE
Add output dir for images

### ISSUE THREAD

**Issue by enrichman** [enrichman/stegosecrets#4]
We can add an output flag to decide where to download the images downloaded by the client.

https://github.com/enrichman/stegosecrets/blob/main/internal/cli/images.go

**Comment by arshad-k7** [comment]
Can you please provide details about it?

**Comment by enrichman** [comment]
Hi @arshad-k7, sure. Basically the `images` command is pretty basic and the directory where to download the images is hardcoded: `fmt.Sprintf("images/%d.jpg", i)`.

https://github.com/enrichman/stegosecrets/blob/main/internal/cli/images.go#L35

It will be nice to have an `-o/--output` flag to select the folder where to download them:

```
stego images -o myimages
```

**Comment by Tashima42** [comment]
Hi @arshad-k7 are you working in this issue? If not, I'd like to be assigned, @enrichman
