### ISSUE TITLE
Version command and variable

### ISSUE THREAD

**Issue by enrichman** [enrichman/stegosecrets#5]
A `Version` var and `version` command is missing.

We should add it in order to populate it with the build flags.

**Comment by misantron** [comment]
#14

**Comment by enrichman** [comment]
Thank you, I left a couple of comments. Please, before opening a PR just discuss the issue, so that can be assigned to you and we are sure that no one is already working on it!

**Comment by misantron** [comment]
Yes sure, sorry for that.

**Comment by enrichman** [comment]
No problem, the project is missing a CONTRIBUTING.md so it's not your fault!

I will add it, and thank you for the PR. 👌
